# -*- coding: utf-8 -*-
"""Gouri_556_Lab2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19gWeaQXj7ouvnE38MqItb6HgREz7exHz
"""

import pandas as pd
df=pd.read_csv("medical_insurance.csv")
df.columns.tolist()
print(df.head(7))
print(df.shape)
print(df.info())
print(df.describe())

numerical_cols=df.select_dtypes(include=['int64','float64']).columns
print("NUMERICAL DATA")
print(list(numerical_cols))
print("\n")
categorical_cols=df.select_dtypes(include=['object']).columns
print("CATEGORICAL DATA")
print(list(numerical_cols))

print(df.isnull().sum())
print(df.duplicated().sum())

df.drop_duplicates(inplace=True)
print(df.duplicated().sum())

"""Why Normalization is Required for the Selected Dataset

The Medical Insurance Cost Prediction dataset contains numerical attributes such as age, bmi, children, and charges. These attributes have different ranges of values. For example, age ranges from 18 to 64, while charges can range from a few thousand to several tens of thousands.

If the data is used without normalization, attributes with larger values may dominate those with smaller values, affecting the performance of machine learning algorithms. Normalization brings all numerical attributes to a common scale, ensuring that each feature contributes equally to the analysis.

Normalization also improves model accuracy, speeds up the training process, and helps machine learning algorithms perform more effectively. Therefore, normalization is an important preprocessing step for the Medical Insurance Cost Prediction dataset.
"""

import matplotlib.pyplot as plt

plt.figure(figsize=(15,4))

# Box Plot
plt.subplot(1,3,1)
df[df.columns].boxplot()
plt.title("Box Plot Before Normalization")

# Bar Graph
plt.subplot(1,3,2)
df[df.columns].head(10).plot(kind='bar', ax=plt.gca())
plt.title("Bar Graph Before Normalization")
plt.xlabel("Records")
plt.ylabel("Values")

# Line Graph
plt.subplot(1,3,3)
plt.plot(df['charges'][:50])
plt.title("Line Graph Before Normalization")
plt.xlabel("Records")
plt.ylabel("Charges")
plt.tight_layout()
plt.show()

from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

minmax_df = pd.DataFrame(
    scaler.fit_transform(df[['age','bmi','children','charges']]),
    columns=['age','bmi','children','charges']
)

import matplotlib.pyplot as plt

plt.figure(figsize=(15,4))

# Box Plot
plt.subplot(1,3,1)
minmax_df.boxplot()
plt.title("Box Plot After Min-Max Normalization")

# Bar Graph
plt.subplot(1,3,2)
minmax_df[['age','bmi','children']].head(10).plot(kind='bar', ax=plt.gca())
plt.title("Bar Graph After Min-Max Normalization")
plt.xlabel("Records")
plt.ylabel("Normalized Values")

# Line Graph
plt.subplot(1,3,3)
plt.plot(minmax_df['charges'][:50])
plt.title("Line Graph After Min-Max Normalization")
plt.xlabel("Records")
plt.ylabel("Normalized Charges")

plt.tight_layout()
plt.show()

from sklearn.preprocessing import MinMaxScaler, StandardScaler
import pandas as pd
import matplotlib.pyplot as plt

# Numerical attributes
num_cols = ['age', 'bmi', 'children', 'charges']

# ==================================================
# MIN-MAX NORMALIZATION
# ==================================================

minmax_scaler = MinMaxScaler()

minmax_df = pd.DataFrame(
    minmax_scaler.fit_transform(df[num_cols]),
    columns=num_cols
)

print("MIN-MAX NORMALIZATION")
print(minmax_df.head())

print("\nORIGINAL VS MIN-MAX NORMALIZED VALUES")
comparison_minmax = pd.concat(
    [df[num_cols].head(), minmax_df.head()],
    axis=1,
    keys=['Original', 'Min-Max']
)
print(comparison_minmax)

# Visualization After Min-Max
plt.figure(figsize=(15,4))

plt.subplot(1,3,1)
minmax_df.boxplot()
plt.title("Box Plot After Min-Max")

plt.subplot(1,3,2)
minmax_df[['age','bmi','children']].head(10).plot(
    kind='bar',
    ax=plt.gca()
)
plt.title("Bar Graph After Min-Max")

plt.subplot(1,3,3)
plt.plot(minmax_df['charges'][:50])
plt.title("Line Graph After Min-Max")

plt.tight_layout()
plt.show()

# ==================================================
# Z-SCORE NORMALIZATION
# ==================================================

zscore_scaler = StandardScaler()

zscore_df = pd.DataFrame(
    zscore_scaler.fit_transform(df[num_cols]),
    columns=num_cols
)

print("\n\nZ-SCORE NORMALIZATION")
print(zscore_df.head())

print("\nMEAN AFTER Z-SCORE")
print(zscore_df.mean())

print("\nSTANDARD DEVIATION AFTER Z-SCORE")
print(zscore_df.std())

# Distribution Analysis
zscore_df.hist(figsize=(8,6))
plt.suptitle("Distribution After Z-Score Normalization")
plt.show()

"""

Comparison of Normalization Techniques

Min-Max Normalization:
• Scales numerical values between 0 and 1.
• Preserves the original relationships among data points.
• Easy to interpret and suitable for algorithms that require bounded values.
• Sensitive to outliers because extreme values affect the scaling range.

Z-Score Normalization:
• Transforms data to have a mean of 0 and a standard deviation of 1.
• Standardizes features with different scales.
• Less sensitive to outliers compared to Min-Max Normalization.
• Suitable for statistical analysis and machine learning algorithms.

Comparison:
• Min-Max Normalization produces values in a fixed range (0 to 1).
• Z-Score Normalization produces values centered around zero with no fixed range.
• Min-Max is useful when the data has no significant outliers.
• Z-Score is preferred when the dataset contains variations and extreme values.

Most Suitable Method for the Healthcare Domain

For the Medical Insurance Cost Prediction dataset, Z-Score Normalization is the most suitable method.

Justification:
• The charges attribute contains large variations and possible outliers.
• Healthcare datasets often have features with different scales and distributions.
• Z-Score Normalization standardizes the data using mean and standard deviation.
• It reduces the effect of extreme values and improves the performance of machine learning models.

Conclusion

Both normalization techniques successfully transformed the numerical attributes. Min-Max Normalization scaled the values between 0 and 1, whereas Z-Score Normalization standardized the data to have a mean of 0 and a standard deviation of 1. For the Medical Insurance Cost Prediction dataset, Z-Score Normalization is more suitable because it handles variations and outliers more effectively."""